# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aec75d52ebd864227ecb979550929a5061438e23ea50efee6351028abaf1e96b242c62cb5eee85bab779435c17f671625b0d612d9091fa2d8a72e42d9f4d766a

test:
  secret_key_base: c1d8c2d3f1ddf2ca4d6c64ffd1e4fc50f05ea2b1f2d9ada2847e354e6d5f8e45a985bea2728b258013e25a7ababd4d63c0603a4c7846981bf1c4025754087993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
